version: "3.7"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    container_name: backend
    hostname: backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html/backend
    ports:
      - 8080:8080
    # networks:
    #   - main
    # environment:
    #   MONGODB_DATABASE: eagle_eye_db
    #   MONGODB_USERNAME:
    #   MONGODB_PASSWORD:
    #   MONGODB_HOSTNAME: mongodb:27017
    #   MONGODB_PORT: '27017'
    #   ENV_DEBUG: 'True'
    #   CELERY_RESULT_BACKEND:  amqp://guest:guest@rabbitmq/%2F
    #   CELERY_TASK_SERIALIZER: 'json'
    #   CELERY_RESULT_SERIALIZER: 'json'
    #   CELERY_TIMEZONE:
    #   REDIS_HOST: redis
    #   BROKER_URL: redis
    #   REDIS_PORT: 6379
    #   CELERY_BROKER_URL: amqp://guest:guest@rabbitmq/%2F
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/var/www/html/frontend
    depends_on:
      - backend
    links:
      # - db
      - backend
    # environment:
    #   - DOC_ENV=local
    #   - SERVER_PORT=5000
    #   # - SERVER_IP=http://54.151.174.78/api
    #   - SERVER_IP=http://127.0.0.1/api

  nginx:
    build:
      context: ./nginx
      dockerfile: ../Dockerfile.nginx
    container_name: nginx
    ports:
      - 80:80
    links:
      - backend
      - frontend
    depends_on:
      - backend
      - frontend
